name: PR Check

on: [pull_request]

jobs:
  check:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
    - name: Format
      run: cargo fmt --all -- --check
    - name: Check
      run: cargo check --locked
    - name: Test
      run: cargo test --locked
    - name: Clippy
      run: cargo clippy --locked --all-targets
    - name: Shell scripts
      run: |
        shellcheck install.sh update.sh uninstall.sh
        bash -n install.sh update.sh uninstall.sh
